### PR TITLE
Exclude excessive build warnings on mac for jdk11 and jdk17

### LINKED ISSUE #3562: MacOS: Harfbuzz throws 70+ megabytes of deprecation warnings during build
**What are you trying to do?**

Build OpenJDK on MacOS x64 and aarch.

**Expected behaviour:**

Under 1mb of output.

**Observed behaviour:**

Over 70mb of output, all along this theme:

```
[2023-12-02T17:17:35.755Z] /Users/admin/workspace/workspace/build-scripts/jobs/jdk11u/jdk11u-mac-aarch64-temurin/workspace/build/src/src/java.desktop/share/native/libharfbuzz/hb-meta.hh:204:44In file included from /Users/admin/workspace/workspace/build-scripts/jobs/jdk11u/jdk11u-mac-aarch64-temurin/workspace/build/src/src/java.desktop/share/native/libharfbuzz/hb-ot-face.cc:27:
[2023-12-02T17:17:35.757Z] :In file included from /Users/admin/workspace/workspace/build-scripts/jobs/jdk11u/jdk11u-mac-aarch64-temurin/workspace/build/src/src/java.desktop/share/native/libharfbuzz/hb-ot-face.hh:32:
[2023-12-02T17:17:35.757Z] In file included from /Users/admin/workspace/workspace/build-scripts/jobs/jdk11u/jdk11u-mac-aarch64-temurin/workspace/build/src/src/java.desktop/share/native/libharfbuzz/hb.hh:530:
[2023-12-02T17:17:35.757Z] /Users/admin/workspace/workspace/build-scripts/jobs/jdk11u/jdk11u-mac-aarch64-temurin/workspace/build/src/src/java.desktop/share/native/libharfbuzz/hb-array.hh:270:64: warning: builtin __has_trivial_assign is deprecated; use __is_trivially_assignable instead [-Wdeprecated-builtins]
[2023-12-02T17:17:35.757Z]             hb_enable_if (!(sizeof (U) < sizeof (long long) && hb_is_trivially_copy_assignable(hb_decay<Type>)))>
[2023-12-02T17:17:35.757Z]                                                                ^
[2023-12-02T17:17:35.757Z] /Users/admin/workspace/workspace/build-scripts/jobs/jdk11u/jdk11u-mac-aarch64-temurin/workspace/build/src/src/java.desktop/share/native/libharfbuzz/hb-meta.hh:204:44: note: expanded from macro 'hb_is_trivially_copy_assignable'
[2023-12-02T17:17:35.757Z] #define hb_is_trivially_copy_assignable(T) __has_trivial_assign(T)
[2023-12-02T17:17:35.757Z]                                            ^
[2023-12-02T17:17:35.757Z] /Users/admin/workspace/workspace/build-scripts/jobs/jdk11u/jdk11u-mac-aarch64-temurin/workspace/build/src/src/java.desktop/share/native/libharfbuzz/hb-iter.hh:277:72: note: in instantiation of template class 'hb_array_t<hb_serialize_context_t::object_t *const>' requested here
[2023-12-02T17:17:35.757Z]   static auto impl (hb_priority<1>) -> decltype (hb_declval (U).iter (), hb_true_type ());
[2023-12-02T17:17:35.757Z]                                                                        ^
[2023-12-02T17:17:35.757Z] /Users/admin/workspace/workspace/build-scripts/jobs/jdk11u/jdk11u-mac-aarch64-temurin/workspace/build/src/src/java.desktop/share/native/libharfbuzz/hb-iter.hh:283:43: note: while substituting explicitly-specified template arguments into function template 'impl' 
[2023-12-02T17:17:35.757Z]    static constexpr bool value = decltype (impl<T> (hb_prioritize))::value;
```

So: Lots of notes and deprecation warnings.

**Any other comments:**

An upstream fix may require harfbuzz to change the minimum xcode they can support, which they may not go for. 

I propose we add a suppression compile flag for the deprecation warnings. 

Not sure how to suppress the notes without suppressing other warnings. 

@gdams - I think this may be related to the Orca move, which changes our Xcode from 12.4 to 15.0.1. What do you think?

### PR DESCRIPTION
**Pull request by adamfarley**
Also included some aggregate logic to avoid cflags overriding other cflags unintentionally

Fixes #3562 

JDK11 (includes fix) test run: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-aarch64-temurin/299/

JDK21 (excludes fix) test run: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-mac-aarch64-temurin/69/

### CODE REVIEW

**Review by smlambert — APPROVED** [review]

File: build-farm/platform-specific-configurations/mac.sh [hunk 1]
```diff
@@ -51,6 +54,13 @@ else
     # JDK17 requires metal (included in full xcode) as does JDK11 on aarch64
     # JDK11 on x64 is matched for consistency
     XCODE_SWITCH_PATH="/Applications/Xcode.app"
+    # JDK11 and 17 on Mac (x86 and aarch) has excessive warnings.
+    # This is due to a harfbuzz fix which is pending backport.
+    # Suppressing the warnings for now to aid triage.
+    if [[ "$JAVA_FEATURE_VERSION" -le 17 ]]; then
```
Comment (sxa) [inline build-farm/platform-specific-configurations/mac.sh:60]: I thought this was only a problem for versions 11 and 17? This will presumably make the change for 8 as well so I would suggest explicitly checking for 11 or 17.

**Review by sxa — COMMENTED** [review]
Presumably the separation of `c_flags_bucket` and `cxx_flags_bucket` instead of just using one variable for this is due to the fact we're only adding the `macosx-version-min` parameter for C++? (Which is a bit surprising - I'd have thought we needed it on both, but that's not related to this PR!)
Other than the version check this LGTM.

File: build-farm/platform-specific-configurations/mac.sh (hunk 1 above)
Comment (adamfarley) [reply build-farm/platform-specific-configurations/mac.sh:60]: Hi Stewart. This will not make the change for 8 as a result of the "if" in line 37:

```
if [ "${JAVA_TO_BUILD}" == "${JDK8_VERSION}" ]
...
else
...
Our code.
```

Comment (sxa) [reply build-farm/platform-specific-configurations/mac.sh:60]: Hmmm ok ... This is getting a bit complex to read but I'll approve.

**Review by sxa — APPROVED** [review]

File: build-farm/platform-specific-configurations/mac.sh (hunk 1 above)
Comment (adamfarley) [reply build-farm/platform-specific-configurations/mac.sh:60]: Thanks
